import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbaar from './components/Navbar'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={clsx(inter.className, 'bg-slate-700')}>
        <Navbaar/>
          <main className=' h-screen p-16'>
          {children}
        </main>
      </body>
    </html>
  )
}
